from __future__ import annotations

import json
from pathlib import Path
import re
import sys
from typing import Any

LEGACY_TYPE_ALIASES: dict[str, str] = {}

AUTO_GENERATED_HEADER = """/**
 * This file is auto-generated by `npm run contracts:generate`.
 * Do not edit it by hand.
 */
"""


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(
            "Usage: python3 scripts/generate_api_types.py <openapi-json-path> <output-ts-path>"
        )

    source_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    document = json.loads(source_path.read_text(encoding="utf-8"))
    schemas: dict[str, dict[str, Any]] = document.get("components", {}).get("schemas", {})

    rendered: list[str] = [AUTO_GENERATED_HEADER.rstrip()]

    for name in sorted(schemas):
        rendered.append("")
        rendered.append(render_named_schema(name, schemas[name]))

    available_schema_names = set(schemas)

    if LEGACY_TYPE_ALIASES:
        rendered.append("")
        rendered.append("// Backward-compatible aliases for older contract consumers.")
        for alias_name, target_name in sorted(LEGACY_TYPE_ALIASES.items()):
            if target_name not in available_schema_names:
                continue
            rendered.append(f"export type {alias_name} = {target_name};")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(rendered).rstrip() + "\n", encoding="utf-8")


def render_named_schema(name: str, schema: dict[str, Any]) -> str:
    if is_empty_object_schema(schema):
        return f"export type {name} = Record<string, never>;"

    if should_render_as_interface(schema):
        return render_interface(name, schema)

    return f"export type {name} = {render_type(schema)};"


def should_render_as_interface(schema: dict[str, Any]) -> bool:
    schema_type = schema.get("type")
    return (
        schema_type == "object"
        or "properties" in schema
        or (
            isinstance(schema.get("additionalProperties"), dict)
            and schema_type not in {"array", "string", "number", "integer", "boolean", "null"}
        )
    )


def render_interface(name: str, schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    lines = [f"export interface {name} {{"]

    additional_properties = schema.get("additionalProperties")
    if additional_properties not in (None, False):
        lines.append(
            f"  [key: string]: {render_additional_properties_type(additional_properties)};"
        )

    for property_name, property_schema in properties.items():
        optional_marker = "" if property_name in required else "?"
        property_label = render_property_name(property_name)
        lines.append(
            f"  {property_label}{optional_marker}: {render_type(property_schema)};"
        )

    lines.append("}")
    return "\n".join(lines)


def is_empty_object_schema(schema: dict[str, Any]) -> bool:
    properties = schema.get("properties", {})
    additional_properties = schema.get("additionalProperties")
    return (
        schema.get("type") == "object"
        and not properties
        and additional_properties in (None, False)
    )


def render_additional_properties_type(schema: Any) -> str:
    if schema is True:
        return "unknown"
    if schema is False:
        return "never"
    if isinstance(schema, dict):
        return render_type(schema)
    return "unknown"


def render_property_name(name: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name):
        return name
    return json.dumps(name)


def render_type(schema: Any) -> str:
    if schema is None:
        return "unknown"

    if not isinstance(schema, dict):
        return "unknown"

    ref = schema.get("$ref")
    if isinstance(ref, str):
        return ref.rsplit("/", 1)[-1]

    enum_values = schema.get("enum")
    if isinstance(enum_values, list) and enum_values:
        return " | ".join(render_literal(value) for value in enum_values)

    if "anyOf" in schema:
        return render_union(schema["anyOf"])

    if "oneOf" in schema:
        return render_union(schema["oneOf"])

    if "allOf" in schema:
        return render_intersection(schema["allOf"])

    schema_type = schema.get("type")
    if schema_type == "array":
        item_type = render_type(schema.get("items"))
        wrapped_item_type = parenthesize_if_needed(item_type)
        return f"{wrapped_item_type}[]"

    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        additional_properties = schema.get("additionalProperties", None)

        if not properties and additional_properties is None:
            return "Record<string, never>"

        members: list[str] = []
        if additional_properties not in (None, False):
            members.append(
                f"[key: string]: {render_additional_properties_type(additional_properties)};"
            )

        for property_name, property_schema in properties.items():
            optional_marker = "" if property_name in required else "?"
            property_label = render_property_name(property_name)
            members.append(
                f"{property_label}{optional_marker}: {render_type(property_schema)};"
            )

        if not members:
            return "Record<string, never>"

        return "{ " + " ".join(members) + " }"

    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"

    return "unknown"


def render_union(options: list[Any]) -> str:
    members = dedupe_preserving_order(render_type(option) for option in options)
    return " | ".join(parenthesize_intersection(member) for member in members) or "unknown"


def render_intersection(options: list[Any]) -> str:
    members = dedupe_preserving_order(render_type(option) for option in options)
    return " & ".join(parenthesize_union(member) for member in members) or "unknown"


def parenthesize_if_needed(rendered_type: str) -> str:
    if "|" in rendered_type or "&" in rendered_type:
        return f"({rendered_type})"
    return rendered_type


def parenthesize_union(rendered_type: str) -> str:
    if "|" in rendered_type:
        return f"({rendered_type})"
    return rendered_type


def parenthesize_intersection(rendered_type: str) -> str:
    if "&" in rendered_type:
        return f"({rendered_type})"
    return rendered_type


def dedupe_preserving_order(values: Any) -> list[str]:
    deduped: list[str] = []
    seen: set[str] = set()
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        deduped.append(value)
    return deduped


def render_literal(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    return str(value)


if __name__ == "__main__":
    main()
